files:
  - letter.tex
params:
  - name: full_name
    prompt: Full Name
    type: str
  - name: address
    prompt: Address
    type: group
    subfields:
      - name: street
        prompt: Street
      - name: city
        prompt: City
      - name: zipcode
        prompt: Zipcode